/** Canonical browser events for cross-module state changes. */
export const PLATFORM_EVENTS = {
  SOURCE_IMPORTED: "SOURCE_IMPORTED",
  SOURCE_CONFIGURED: "SOURCE_CONFIGURED",
  ACTIVE_DATASET_CHANGED: "ACTIVE_DATASET_CHANGED",
  ENTERPRISE_CONTEXT_CHANGED: "ENTERPRISE_CONTEXT_CHANGED",
  DOMAIN_CONTEXT_CHANGED: "DOMAIN_CONTEXT_CHANGED",
  PRESENTATION_UPDATED: "PRESENTATION_UPDATED",
  AUTH_STATE_CHANGED: "AUTH_STATE_CHANGED",
  WORKSPACE_REGISTRY_CHANGED: "WORKSPACE_REGISTRY_CHANGED",
  DATA_SOURCE_STATE_CHANGED: "DATA_SOURCE_STATE_CHANGED",
  DISCOVERY_ARTIFACT_GENERATED: "DISCOVERY_ARTIFACT_GENERATED",
  EVIDENCE_ARTIFACT_GENERATED: "EVIDENCE_ARTIFACT_GENERATED",
  SEMANTIC_ARTIFACT_GENERATED: "SEMANTIC_ARTIFACT_GENERATED",
  SEMANTIC_REVIEW_STARTED: "SEMANTIC_REVIEW_STARTED",
  SEMANTIC_FIELD_CONFIRMED: "SEMANTIC_FIELD_CONFIRMED",
  SEMANTIC_FIELD_REJECTED: "SEMANTIC_FIELD_REJECTED",
  SEMANTIC_FIELD_KEPT_ORIGINAL: "SEMANTIC_FIELD_KEPT_ORIGINAL",
  SEMANTIC_CUSTOM_INTERPRETATION_RECORDED: "SEMANTIC_CUSTOM_INTERPRETATION_RECORDED",
  SEMANTIC_DECISION_DEFERRED: "SEMANTIC_DECISION_DEFERRED",
  SEMANTIC_CONFIRMATION_ARTIFACT_GENERATED: "SEMANTIC_CONFIRMATION_ARTIFACT_GENERATED",
  SOURCE_UNDERSTANDING_CONFIRMED: "SOURCE_UNDERSTANDING_CONFIRMED",
  SEMANTIC_CONFIRMATION_INVALIDATED: "SEMANTIC_CONFIRMATION_INVALIDATED",
  TRUST_ASSESSMENT_STARTED: "TRUST_ASSESSMENT_STARTED",
  TRUST_ARTIFACT_GENERATED: "TRUST_ARTIFACT_GENERATED",
  TRUST_ASSESSMENT_BLOCKED: "TRUST_ASSESSMENT_BLOCKED",
  TRUST_ARTIFACT_INVALIDATED: "TRUST_ARTIFACT_INVALIDATED",
  BUSINESS_ANALYSIS_STARTED: "BUSINESS_ANALYSIS_STARTED",
  BUSINESS_ARTIFACT_GENERATED: "BUSINESS_ARTIFACT_GENERATED",
  BUSINESS_ANALYSIS_BLOCKED: "BUSINESS_ANALYSIS_BLOCKED",
  FINANCIAL_CLASSIFICATION_STARTED: "FINANCIAL_CLASSIFICATION_STARTED",
  FINANCIAL_CLASSIFICATION_DECISION_RECORDED: "FINANCIAL_CLASSIFICATION_DECISION_RECORDED",
  FINANCIAL_CLASSIFICATION_CONFIRMED: "FINANCIAL_CLASSIFICATION_CONFIRMED",
  FINANCIAL_CLASSIFICATION_INVALIDATED: "FINANCIAL_CLASSIFICATION_INVALIDATED",
  FINANCIAL_CLASSIFICATION_SUPERSEDED: "FINANCIAL_CLASSIFICATION_SUPERSEDED",
  DRE_COMPOSITION_STARTED: "DRE_COMPOSITION_STARTED",
  DRE_ARTIFACT_GENERATED: "DRE_ARTIFACT_GENERATED",
  DRE_COMPOSITION_BLOCKED: "DRE_COMPOSITION_BLOCKED",
  DRE_ARTIFACT_INVALIDATED: "DRE_ARTIFACT_INVALIDATED",
  DRE_ARTIFACT_SUPERSEDED: "DRE_ARTIFACT_SUPERSEDED",
  DRE_RECONCILIATION_STARTED: "DRE_RECONCILIATION_STARTED",
  DRE_RECONCILIATION_ARTIFACT_GENERATED: "DRE_RECONCILIATION_ARTIFACT_GENERATED",
  DRE_RECONCILIATION_BLOCKED: "DRE_RECONCILIATION_BLOCKED",
  DRE_RECONCILIATION_INVALIDATED: "DRE_RECONCILIATION_INVALIDATED",
  DRE_RECONCILIATION_SUPERSEDED: "DRE_RECONCILIATION_SUPERSEDED",
  PRELIMINARY_ANALYSIS_STARTED: "PRELIMINARY_ANALYSIS_STARTED",
  PRELIMINARY_ANALYSIS_ARTIFACT_GENERATED: "PRELIMINARY_ANALYSIS_ARTIFACT_GENERATED",
  PRELIMINARY_ANALYSIS_BLOCKED: "PRELIMINARY_ANALYSIS_BLOCKED",
  PRELIMINARY_ANALYSIS_INVALIDATED: "PRELIMINARY_ANALYSIS_INVALIDATED",
} as const;

export type PlatformEventName = typeof PLATFORM_EVENTS[keyof typeof PLATFORM_EVENTS];

export function dispatchPlatformEvent<T>(name: PlatformEventName, detail: T): void {
  if (typeof window === "undefined" || typeof CustomEvent === "undefined") return;
  window.dispatchEvent(new CustomEvent(name, { detail }));
}

export function subscribePlatformEvent<T>(
  name: PlatformEventName,
  listener: (detail: T) => void,
): () => void {
  if (typeof window === "undefined") return () => undefined;
  const handler = (event: Event) => listener((event as CustomEvent<T>).detail);
  window.addEventListener(name, handler);
  return () => window.removeEventListener(name, handler);
}
